# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='altitude',
            field=models.FloatField(help_text='Altitude in meters'),
        ),
        migrations.AlterField(
            model_name='point',
            name='angle',
            field=models.FloatField(help_text='Angle in degrees'),
        ),
        migrations.AlterField(
            model_name='point',
            name='lat',
            field=models.FloatField(help_text='Latitude in decimal degrees'),
        ),
        migrations.AlterField(
            model_name='point',
            name='lon',
            field=models.FloatField(help_text='Longitude in decimal degrees'),
        ),
    ]
