# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 01:09
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(max_length=32)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='RawReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('raw_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReadingStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reading_time', models.DateTimeField()),
                ('fix', models.BooleanField()),
                ('speed', models.FloatField()),
                ('satellite_count', models.PositiveSmallIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Point')),
            ],
            options={
                'ordering': ('reading_time',),
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_data.Device')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='GasReading',
            fields=[
                ('reading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensor_data.Reading')),
            ],
            options={
                'abstract': False,
            },
            bases=('sensor_data.reading',),
        ),
        migrations.CreateModel(
            name='PMReading',
            fields=[
                ('reading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensor_data.Reading')),
            ],
            options={
                'abstract': False,
            },
            bases=('sensor_data.reading',),
        ),
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('reading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensor_data.Reading')),
                ('header', models.PositiveSmallIntegerField()),
                ('temperature', models.FloatField(verbose_name='Temperature in Celsius')),
                ('temperature_lowpass', models.FloatField(verbose_name='Temperature in Celsius lowpass filtered')),
            ],
            options={
                'abstract': False,
            },
            bases=('sensor_data.reading',),
        ),
        migrations.AddField(
            model_name='reading',
            name='raw_reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_data.RawReading'),
        ),
        migrations.AddField(
            model_name='reading',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_data.Sensor'),
        ),
        migrations.AddField(
            model_name='reading',
            name='stamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_data.ReadingStamp'),
        ),
    ]
