# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='reading_id',
            field=models.PositiveSmallIntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reading',
            name='raw_reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensor_data.RawReading'),
        ),
        migrations.AlterField(
            model_name='readingstamp',
            name='speed',
            field=models.FloatField(help_text='Speed in meters per second'),
        ),
    ]
